### ISSUE TITLE
Please make this UserCSS

### ISSUE THREAD

**Issue by skank** [Bloumbs/PyPI-Dark#1]
Thanks for making this. Exactly what I was looking for!

All though the theme is great could you please make it [UserCss](https://github.com/openstyles/stylus/wiki/Usercss) compatible?

Among other things, it will _preserve user privacy_ and allow automatic updates with stylus.
Thanks for considering.

**Comment by Bloumbs** [comment]
@skank I guess I just didn't notice your issue all that time ago. I'm sorry about that. I haven't really been checking in on this repo.

Its probably completely off your mind now at this point, but I updated the theme slightly, and made it UserCSS compatible [here](https://raw.githubusercontent.com/Bloumbs/PyPI-Dark/master/pypi-dark.user.css). I think. I hope I did things correctly. :)
